name: Haiku

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Build on Haiku
      uses: cross-platform-actions/action@v0.30.0
      with:
        operating_system: haiku
        version: r1beta5
        image_url: 'https://github.com/cross-platform-actions/haiku-builder/releases/download/v0.0.1/haiku-r1beta5-x86-64.qcow2'
        run: |
          echo yes | pkgman install cmake ninja glu_devel libvorbis_devel
          cmake . -B build --preset=ci-gcc
          cmake --build build --preset ninja-quiet
