name: PSP

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev:latest
      volumes:
        - ${{ github.workspace }}:/src
    steps:
    - name: 🎮 Setup tools
      run: apk add ninja-build
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: ⚒ Build with gcc
      run: |
        cmake . -B build --preset=ci-psp
        cmake --build build --preset ninja-quiet
